global:
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['ec2-52-3-226-63.compute-1.amazonaws.com:9093']
 
rule_files:
- alert_rules.yml
scrape_configs:
  - job_name: 'prometheus-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-52-3-226-63.compute-1.amazonaws.com:9090']
  - job_name: 'prometheus-node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-52-3-226-63.compute-1.amazonaws.com:9100']
  - job_name: 'WebServers'
    scrape_interval: 5s
    static_configs:
      - targets: ['ec2-44-197-180-56.compute-1.amazonaws.com:9100','ec2-3-91-19-60.compute-1.amazonaws.com:9100']