ssh_key_path: C:\SUREDELETELATER\DevOpsB23\K8S\LaptopKey.pem
cluster_name: devopsb23cluster
kubernetes_version: v1.22.7-rancher1-2
nodes:
  - address: 44.198.175.16
    #internal_address: 10.1.3.91
    user: ubuntu
    role: [controlplane, worker, etcd]
    hostname_override: master01
  - address: 44.203.213.134
    #internal_address: 10.1.14.192
    user: ubuntu
    role: [worker]
    hostname_override: worker01
  - address: 44.203.80.241
    #internal_address: 10.1.9.72
    user: ubuntu
    role: [worker]
    hostname_override: worker02

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

network:
  plugin: flannel
  options:
    flannel_iface: eth0
    flannel_backend_type: vxlan
    flannel_autoscaler_priority_class_name: system-cluster-critical # Available as of RKE v1.2.6+
    flannel_priority_class_name: system-cluster-critical # Available as of RKE v1.2.6+
